const data = [
  {
    id: 1,
    title: 'Еда',
    cards: [
      {
        id: 2,
        image: 'https://i.ibb.co/3Cy2RwR/delivery.png',
        text: 'Delivery Club',
        subtext: 'Заказывайте еду из кафе и ресторанов',
        link: 'https://www.delivery-club.ru/',
        linkAndroid: 'https://play.google.com/store/apps/details?id=com.deliveryclub',
        linkIOS: 'https://itunes.apple.com/app/id436145623?mt=8',
      },
      {
        id: 3,
        image: 'https://i.ibb.co/Pm0RMRV/samokat.png',
        text: 'Самокат',
        subtext: 'Закажите молоко к завтраку, шоколадку к чаю или продукты на неделю и получите свой заказ в течение 15 минут',
        link: 'https://samokat.ru/',
        linkIOS: 'https://app.adjust.com/jcfuci6?redirect=https://apps.apple.com/ru/app/id1401500803',
        linkAndroid: 'https://app.adjust.com/jcfuci6?redirect=https://play.google.com/store/apps/details?id=ru.sbcs.store',
      },
      {
        id: 5,
        image: 'https://i.ibb.co/X2jB3rC/narayone.png',
        text: 'Кухня на районе',
        subtext: 'Сделайте заказ в мобильном приложении и получите готовую еду в течение 30 минут',
        link: 'http://web.localkitchen.ru/?utm_source=sberbank.ru',
        linkAndroid: 'https://localkitchen.onelink.me/O9JV/9b7f98da',
        linkIOS: 'https://localkitchen.onelink.me/O9JV/9b7f98da',
      },
      {
        id: 6,
        image: 'https://i.ibb.co/SRXgSPH/levelkitchen.png',
        text: 'Level Kitchen',
        subtext: 'Заказывайте здоровое питание на несколько дней или на весь месяц',
        link: 'https://levelkitchen.com/',
      },
      {
        id: 7,
        image: 'https://i.ibb.co/DLPsH9G/sbermarket.png',
        text: 'СберМаркет',
        subtext: 'Закажите продукты из любимого магазина, а СберМаркет доставит ваш заказ за несколько часов',
        link: 'https://sbermarket.ru/',
        linkIOS: 'https://app.adjust.com/kfrpj8y',
        linkAndroid: 'https://app.adjust.com/kfrpj8y',
      },
      {
        id: 8,
        image: 'https://i.ibb.co/MGqbrXK/sberfood.png',
        text: 'СберФуд',
        subtext: 'Забронируйте стол, оплатите счет или разделите его с друзьями, оставляйте чаевые и копите бонусы в одном приложении',
        link: 'https://sberfood.ru/',
        linkIOS: 'https://go.onelink.me/app/c29eac62',
        linkAndroid: 'https://go.onelink.me/app/885b83b6',
      },
    ],
  },
  {
    id: 9,
    title: 'Товары',
    cards: [
      {
        id: 10,
        image: 'https://i.ibb.co/Gnhj9GC/sberprime.png',
        text: 'СберПрайм',
        subtext: 'Получите специальные предложения от сервисов экосистемы Сбера',
        link: 'https://www.sber.ru/sberprime',
      },
    ],
  },
  {
    id: 11,
    title: 'Транспорт',
    cards: [
      {
        id: 12,
        image: 'https://i.ibb.co/4Yc7BzX/setelem.png',
        text: 'Сетелем',
        subtext: 'Оформите автокредит онлайн',
        link: 'https://www.cetelem.ru/',
      },
      {
        id: 13,
        image: 'https://i.ibb.co/jfWd7SX/citymobile.png',
        text: 'Ситимобил',
        subtext: 'Заказывайте такси в удобном мобильном приложении',
        link: 'https://city-mobil.ru/',
        linkIOS: 'https://apps.apple.com/app/id579220388',
        linkAndroid: 'https://play.google.com/store/apps/details?id=com.citymobil',
      },
      {
        id: 14,
        image: 'https://i.ibb.co/D8L7nWB/sberbank.png',
        text: 'Осаго онлайн',
        subtext: 'Сравните цены и оформите полис онлайн',
        link: 'https://osago.sberbank.ru/',
      },
      {
        id: 15,
        image: 'https://i.ibb.co/M1x5Ttm/youdrive.png',
        text: 'Юдрайв',
        subtext: 'Каршеринг с быстрой онлайн-регистрацией и гибкими тарифами',
        link: 'https://youdrive.today/',
        linkIOS: 'https://itunes.apple.com/ru/app/youdrive/id989836024?l=en',
        linkAndroid: 'https://play.google.com/store/apps/details?id=youdrive.today',
      },
      {
        id: 16,
        image: 'https://i.ibb.co/0VBP8jF/gis2.png',
        text: '2ГИС',
        subtext: 'Стройте маршруты, ищите точные адреса и контакты нужных вам заведений, читайте отзывы и заказывайте товары',
        link: 'https://2gis.ru/',
        linkIOS: 'https://apps.apple.com/US/app/id481627348?mt=8',
        linkAndroid: 'https://play.google.com/store/apps/details?id=ru.dublgis.dgismobile',
      },
    ],
  },
  // {
  //   id: 17,
  //   title: 'Здоровье',
  //   cards: [
  //     {
  //       id: 18,
  //       image: '',
  //       text: '',
  //       subtext: '',
  //       link: '',
  //       linkAndroid: '',
  //       linkIOS: '',
  //     },
  //   ],
  // },
  {
    id: 22,
    title: 'Карьера',
    cards: [
      {
        id: 23,
        image: 'https://i.ibb.co/jLdT3bd/rabota.png',
        text: 'Работа.ру',
        subtext: 'Откликайтесь на вакансии, выкладывайте резюме или ищите сотрудников',
        link: 'https://www.rabota.ru/',
        linkAndroid: 'https://sbol.onelink.me/INEy/905eb725',
        linkIOS: 'https://sbol.onelink.me/INEy/905eb725',
      },
    ],
  },
  {
    id: 26,
    title: 'Образование',
    cards: [
      {
        id: 27,
        image: 'https://i.ibb.co/1MYjDLb/sberclass.png',
        text: 'СберКласс',
        subtext: 'СберКласс — современные инструменты и новые форматы обучения и взаимодействия',
        link: 'https://sberclass.ru',
      },
    ],
  },
  {
    id: 29,
    title: 'Финансы',
    cards: [
      {
        id: 30,
        image: 'https://i.ibb.co/nf338yj/yamoney.png',
        text: 'ЮMoney',
        subtext: 'Онлайн-платежи и переводы, электронный кошелек и карты',
        link: 'https://yoomoney.ru',
        linkAndroid: 'https://promo.yoomoney.ru/app',
        linkIOS: 'https://promo.yoomoney.ru/app',
      },
      {
        id: 31,
        image: 'https://i.ibb.co/D8L7nWB/sberbank.png',
        text: 'СберБанк Онлайн',
        subtext: 'Удобные переводы и платежи, доступ к банковским сервисам с ПК и смартфона',
        link: 'https://www.sberbank.ru/ru/person/dist_services/inner_apps',
        linkIOS: 'https://sberbankonline.onelink.me/46WQ/e46d737',
        linkAndroid: 'https://play.google.com/store/apps/details?id=ru.sberbankmobile',
      },
      {
        id: 32,
        image: 'https://i.ibb.co/p1RSKCX/spasibo.png',
        text: 'Спасибо',
        subtext: 'Программа лояльности для клиентов банка: получайте возврат бонусами за покупки',
        link: 'https://spasibosberbank.ru',
        linkIOS: 'https://itunes.apple.com/us/app/spasibo-ot-sberbanka/id899525659',
        linkAndroid: 'https://play.google.com/store/apps/details?id=ru.sberbank.spasibo',
      },
    ],
  },
  {
    id: 40,
    title: 'Развлечения',
    cards: [
      {
        id: 41,
        image: 'https://i.ibb.co/w4kGjsB/okko.png',
        text: 'Okko',
        subtext: 'Смотрите фильмы и сериалы без рекламы на любом устройстве',
        link: 'https://okko.tv',
        linkIOS: 'https://apps.apple.com/RU/app/id448868000',
        linkAndroid: 'https://play.google.com/store/apps/details?id=ru.more.play',
      },
      {
        id: 42,
        image: 'https://i.ibb.co/SBmHH19/kassa.png',
        text: 'Афиша',
        subtext: 'Онлайн-сервис по продаже билетов в кино, театр, на концерты и другие мероприятия',
        link: 'https://kassa.rambler.ru/movie?openauthframe=1',
        linkIOS: 'https://apps.apple.com/ru/app/рамблер-касса/id905950888',
        linkAndroid: 'https://play.google.com/store/apps/details?id=ru.rambler.kassa&hl=ru',
      },
    ],
  },
  {
    id: 60,
    title: 'Медиа',
    cards: [
      {
        id: 61,
        image: 'https://i.ibb.co/0Zh4gCL/souz.png',
        text: 'Союзмультфильм',
        subtext: 'Развитие российской анимации, создание развивающего контента для детей',
        link: 'https://souzmult.ru/',
      },
      {
        id: 62,
        image: 'https://i.ibb.co/txYgf0j/segmento.png',
        text: 'Сегменто',
        subtext: 'Поиск аудитории в социальных сетях, автоматизация рекламных кампаний, размещение рекламы в мобильных приложениях',
        link: 'https://segmento.ru/',
      },
    ],
  },
  {
    id: 50,
    title: 'Недвижимость',
    cards: [
      {
        id: 51,
        image: 'https://i.ibb.co/THLhS6v/domclick.png',
        text: 'ДомКлик',
        subtext: 'Поиск, покупка и безопасная сделка с жильем',
        link: 'https://my.domclick.ru/easy-deal',
        linkAndroid: 'https://play.google.com/store/apps/details?id=ru.domclick.mortgage',
        linkIOS: 'https://itunes.apple.com/ru/app/домклик/id1143031400',
      },
      {
        id: 52,
        image: 'https://i.ibb.co/jyBjykL/sov-teck.png',
        text: 'СовТех',
        subtext: 'Техническое обслуживание недвижимости',
        link: 'https://совтех.рф/',
      },
    ],
  },
  {
    id: 70,
    title: 'Технологии',
    page: '#',
    btnText: 'Больше технологичных решений',
    cards: [
      {
        id: 71,
        image: 'https://i.ibb.co/w7h5W0K/bi-zone.png',
        text: 'BI.ZONE',
        subtext: 'Разработчик в области кибербезопасности',
        link: 'https://bi.zone/ru',
      },
      {
        id: 72,
        image: 'https://i.ibb.co/hdNChjg/vision.png',
        text: 'VisionLabs',
        subtext: 'Разработка продуктов и решений в области компьютерного зрения и машинного обучения',
        link: 'https://visionlabs.ai/ru/company/about-us',
      },
      {
        id: 73,
        image: 'https://i.ibb.co/cL41PTb/cloud.png',
        text: 'SberCloud',
        subtext: 'Облачная платформа Сбера - от хранилища до машинного обучения',
        link: 'https://sbercloud.ru/ru',
      },
      {
        id: 74,
        image: 'https://i.ibb.co/pZNn2TY/dev.jpg',
        text: 'SberDevices',
        subtext: 'Разработчик умных устройств и программного обеспечения',
        link: 'https://www.sber.ru/salute',
      },
    ],
  },
];

module.exports = data;
